FROM debian:bookworm-slim

EXPOSE 8080

WORKDIR /workspace

RUN apt update && \
    apt install --yes ca-certificates curl git gnupg nano

RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
    apt update && \
    apt install nodejs --yes && \
    npm install --global npm
